config/routes.rb
Rails.application.routes.draw do

  # active admin urls
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # categories controller 
  resources :categories
  
  # items controller
  resources :items

  # a user can sign up multiple times
  resources :users
  # users can only make one session
  resource :session
  # users should only be able to edit one account
  resource :account

  get "about", to: "pages#about"

  root "pages#home"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_items
  has_many :items, through: :category_items
  validates :title, presence: true
end

app/models/category_item.rb
class CategoryItem < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :category_items
  has_many :categories, through: :category_items
  validates :title, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true,  uniqueness: true
  validates :stripe_token, presence: true
  validates :subscription_plan, inclusion: { in: ["price_1K1VckAKLJKLXKWGEGRdN7i2", "price_1K1VaIAKLJKLXKWGV5BRVSyw"]}

  has_secure_password

  def save_and_subscribe
    # check if user is valid
    # check the stripe token 
    # if everything is okay add a stripe customer
    # make the stripe customer added to the plan they picked

    if self.valid?
      Stripe.api_key = Rails.application.credentials[Rails.env.to_sym][:stripe_secret_key]
      # create stripe customer 
      customer = Stripe::Customer.create(
        source: self.stripe_token,
        description: self.email 
      )
      # make a subscription on stripe
      subscription = Stripe::Subscription.create(
          customer: customer.id, 
          items: [{ plan: self.subscription_plan}]
      )
      # save the customer id to the database 
      self.stripe_customer = customer.id
      # save the subscription id tothe datatbase
      self.stripe_subscription = subscription.id
      # save everythign
      self.save
      else 
        false
    end 

    rescue Stripe::CardError => e
      # this is from stripe
      @message = e.json_body[:error][:message]
      # then add to the model errors
      self.errors.add(:stripe_token, @message)
      # return false to our controller
      false
  end 

  def update_with_stripe(form_params)
    Stripe.api_key = Rails.application.credentials[Rails.env.to_sym][:stripe_secret_key]
    # update the model with form_params
    # check if it is valid
    # if it is valid update stripe
    # then update the database
    self.assign_attributes(form_params)
    if self.valid?
      # get the subscription from stripe
      subscription = Stripe::Subscription.retrieve(self.stripe_subscription)
      # get the first item from the subscription
      item_id = subscription.items.data[0].id
      # make our new items list
      items = [
        { id: item_id, plan: self.subscription_plan }
      ]
      # update our subscription with the new items
      subscription.items = items
      # save the subscription to stripe
      subscription.save
      # save our data to the database
      self.save
    else 
      false
    end
  end 

  def destroy_and_unsubscribe
    # get the subscription for stripe
    subscription = Stripe::Subscription.retrieve(self.stripe_subscription)
    # delete that subscription
    subscription.delete
    # remove the user completely
    self.destroy
  end 

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def edit
    @user = @current_user
  end 

  def update
    @user = @current_user
    if @user.update_with_stripe(form_params)
      flash[:success] = "Your account has been updated"
      redirect_to root_path
    else 
      render "edit"
    end 
  end 

  def destroy
    # deletes and unsubscribes
    @current_user.destroy_and_unsubscribe
    # remove the session
    reset_session
    # redirect to home page
    redirect_to root_path
  end 

  def form_params
    params.require(:user).permit(:subscription_plan)
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # this makes current_user available to use in views
  helper_method :current_user, :is_logged_in?
  # run this on every single page and action
  before_action :current_user
  # this is only able to be used in controllers
  def current_user
    if is_logged_in?
      @current_user = User.find(session[:user_id])
    else 
      @current_user = nil
    end 
    @current_user
  end

  def is_logged_in?
    session[:user_id].present?
  end

  def force_login
    unless is_logged_in?
      flash[:error] = "You are not logged in"
      redirect_to root_path
    end 
  end 

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index 
    @categories = Category.all
  end 

  def show 
    @category = Category.find(params[:id])
  end 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :force_login

  def index 
    # if theres a search filter
    if params[:q].present?
      # this is where we search
      @items = Item.where("lower(title) LIKE ?", "%" + params[:q].downcase + "%")
    else 
      #if not show all 
      @items = Item.all
    end 
  end 

  def show 
    @item = Item.find(params[:id])
  end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if is_logged_in?
      redirect_to items_path
    end 
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
    #we dont need any variables in here because we are not adding to the database just creating a new session
  end 

  def create 
    @username = form_params[:username]
    @password = form_params[:password]
    @user = User.find_by(username: @username).try(:authenticate, @password)
    if @user
      session[:user_id] = @user.id
      flash[:success] = "You are now logged in"
      redirect_to root_path
    else
      render "new"
    end
  end 

  def destroy
    reset_session
    flash[:success] = "You are now logged out"
    redirect_to root_path
  end 

  def form_params 
    params.require(:session).permit(:username, :password)
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new 
    @user = User.new
  end 

  def create 
    @user = User.new(form_params)
    #check if the user can save 
    if @user.save_and_subscribe
      # keep hold of that user
      session[:user_id] = @user.id
      # let the user know theyve signed up
      flash[:success] = "Welcome to Source"

      redirect_to root_path
    else  
      render "new"
    end 
  end 

  def form_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :subscription_plan, :stripe_token)
  end 
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def format_categories(categories)
    links = categories.map do |cat| 
      link_to cat.title, category_path(cat)
    end 
    links.to_sentence.html_safe
  end 
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/edit.html.erb
<h1> Edit account </h1>
<%= simple_form_for @user, url:account_path do |f| %>
  <%= f.input :subscription_plan, as: :select, collection:
  [['Basic Subscription - £9.99/mo', 'price_1K1VaIAKLJKLXKWGV5BRVSyw'], ['Pro Subscription - $19.99/mo', 'price_1K1VckAKLJKLXKWGEGRdN7i2']], 
  include_blank: false %>
  <%= f.button :submit, "Update account" %>

<% end %>

<p>
  <%= link_to "Delete account", account_path, method: :delete, 
  data: { confirm: "Are you sure you want to delete your account?" } %>
</p>

app/views/categories/index.html.erb
<h1> Categories </h1>
<% @categories.each do |cat| %>
  <p><%= link_to cat.title, category_path(cat) %></p>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>
<p><%= link_to "Back to all categories", categories_path %></p>


<div class="items-grid">
<%= render partial: "items/item", collection: @category.items.all %>
</div>

app/views/items/_item.html.erb
<div class="item">
<%= link_to item_path(item) do %>
  <h2><%= item.title %></h2>
  <%= image_tag (item.image.medium.url) %>
<% end %>
</div>

app/views/items/index.html.erb
<h1>Photos</h1>

<form action="">
  <input type="text" name="q" value="<%= params[:q] %>">
</form>
<div class="items-grid">
<%= render partial: "item", collection: @items %>
</div>

app/views/items/show.html.erb
<div class="item-page">
<h1><%= @item.title %></h1>

<p>
<strong> Categories: </strong>
<%= format_categories @item.categories %>
</p>

<%= simple_format @item.description %>
<%= image_tag (@item.image.medium.url) %>
<p>
<%= link_to "Download", @item.image.url, download: true %>
</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Source</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:success].present? %>
    <div class="success">
      <%= flash[:success] %>
    </div>
    <% end %>

    <% if flash[:error].present? %>
    <div class="error">
      <%= flash[:error] %>
    </div>
    <% end %>
    <div class="container">
    <header>
      <h1><%= link_to "Source", root_path %></h1>
      <nav>
      <% if is_logged_in? %>
        <strong class="username"><%= @current_user.username %></strong>
        <%= link_to "All Photos", items_path %>
        <%= link_to "All Categories", categories_path %>
        <%= link_to "Account", edit_account_path %>
        <%= link_to "Log out", session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_path %>
          <%= link_to "Log in", new_session_path %>
      <%end %>
      </nav>
    </header>
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h2>Welcome to Source</h2>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet elit varius, dignissim erat eu, posuere ipsum. Etiam efficitur tempus velit, nec mattis mauris feugiat in. Aenean consectetur sed quam sed facilisis. Etiam blandit efficitur aliquet. Quisque orci sem, interdum vitae pretium a, vestibulum non quam. Sed nec massa egestas, dictum tellus sed, ultrices nulla. Sed aliquam et tellus placerat egestas. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla mollis sit amet diam et sagittis. Aenean luctus placerat orci nec convallis. Nunc eget nulla id nisl elementum porta.
</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= simple_form_for @user do |f| %>
  <%= f.input :name %>
  <%= f.input :username %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>

  <%= f.input :subscription_plan, as: :select, collection:
  [['Basic Subscription - £9.99/mo', 'price_1K1VaIAKLJKLXKWGV5BRVSyw'], ['Pro Subscription - $19.99/mo', 'price_1K1VckAKLJKLXKWGEGRdN7i2']], include_blank: false %>

  <div id="card-errors">
    <% @user.errors[:stripe_token].each do |e| %>
      <%= e %>
      <% end %>
  </div>
  <div id="card-element"></div>

  <%= f.button :submit, "Sign up" %>

<% end %>

<script>
   var stripe = Stripe("<%= Rails.application.credentials[Rails.env.to_sym][:stripe_public_key] %>")
    var elements = stripe.elements();

   var card = elements.create("card");
    card.mount("#card-element");

   var form = document.getElementById('new_user');
   form.addEventListener('submit', (event) => {
       event.preventDefault();
       stripe.createToken(card).then((result) => {
           if (result.error) {
           var errorElement = document.getElementById("card-errors");
           errorElement.textContent = result.error.message;
                     } else {
               stripeTokenHandler(result.token);
           }
       });
   });
   var stripeTokenHandler = (token) => {
       console.log(token.id);
       var form = document.getElementById('new_user');
       var hiddenInput = document.createElement('input');
       hiddenInput.setAttribute('type', 'hidden');
       hiddenInput.setAttribute('name', 'user[stripe_token]');
       hiddenInput.setAttribute('value', token.id);
       form.appendChild(hiddenInput);
   form.submit();
   }
</script>